linux/sysfs: Fix device path
Commit 5c28f5a45c55 ("linux: Move sysfs into separate package") updated
the order in which the arguments to the __init__ for the 'class Device'
are parsed and this causes the following failure to occur when running
drivers test ...

 $ ./tests/boot.py --verbose drivers
 boot: drivers: board: NVIDIA Jetson Xavier Development Kit
 boot: drivers:   driver: /sys/bus/platform/drivers/tegra-host1x ... exists
 Traceback (most recent call last):
   File "./tests/boot.py", line 168, in <module>
     runner.standalone(module)
   File "/home/ubuntu/tegra-tests/tests/runner.py", line 147, in standalone
     log.test(log = log, args = args)
   File "./tests/boot.py", line 114, in __call__
     for device in driver.devices():
   File "/home/ubuntu/tegra-tests/linux/sysfs/__init__.py", line 156, in devices
     device = Device(os.path.realpath(path))
   File "/home/ubuntu/tegra-tests/linux/sysfs/__init__.py", line 114, in __init__
     path, name = split_path(parent.full_path, name)
 AttributeError: 'str' object has no attribute 'full_path'

Fix this by ensuring the 'path' argument is set as needed when
initialising the device in the 'Driver' class.

Signed-off-by: Jon Hunter <jonathanh@nvidia.com>
Signed-off-by: Thierry Reding <treding@nvidia.com>